version: 2

jobs:
  checkout_and_compile:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/set.js
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "4c:c0:3a:d9:06:58:2b:4c:13:dc:00:48:e8:55:20:8a"
      - run:
          name: Check SSH Keys
          command: ssh-add -L # This shows that the key was successfully added
      - restore_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Set Up Environment Variables
          command: cp .env.default .env
      - run:
          name: Test npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/set.js/.npmrc
      - run:
          name: Inject Truffle
          command: yarn global add truffle --ignore-engines
      - run:
          name: Fetch Dependencies
          command: yarn install --network-concurrency 1
      - save_cache:
          key: module-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Transpile
          command: yarn build
      - save_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/set.js
  test:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/set.js
    parallelism: 2
    steps:
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test RPC
          command: yarn chain
          background: true
      - run:
          name: Wait for chain to start
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=30 --read-timeout=30 --timeout=20 -t 100 http://localhost:8545
            :
      - run:
          name: Jest
          no_output_timeout: 30m
          command: |
            mkdir -p /tmp/test-results
            TEST_FILES="$(circleci tests glob "./test/**/*.spec.ts" | circleci tests split)"
            echo $TEST_FILES
            yarn test --findRelatedTests ${TEST_FILES}
          when: always
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_and_compile
      - test:
          requires:
            - checkout_and_compile
